### ISSUE TITLE
Cannot read property 'injectedReducers' of undefined`

### ISSUE THREAD

**Issue by thehig** [GuillaumeCisco/redux-reducers-injector#8]
As of the latest update I am getting a weird error where there was none before. `TypeError: Cannot read property 'injectedReducers' of undefined`.

Everything was working fine before this, and I'm not sure how to proceed. My guess is it has something to do with [this](https://github.com/GuillaumeCisco/redux-reducers-injector/blob/50e8ce2420cb4bf4cfe7b04a383e48b262c0e80e/src/ReduxInjector.js#L61)

**Comment by thehig** [comment]
A similar issue has arisen in the `redux-sagas-injector` project

**Comment by thehig** [comment]
I have this issue client side.

I'm making my calls in a Saga. Code below

```javascript

/**
 * Take a list of modules, import and inject them, create a RouteMap singleton to reference the Components, then inject the paths into state
 */
function* moduleLoaderSaga(/*action*/) {
  const modules = yield select(Selectors.getModules);

  // Load the modules specified, then destructure the parts we care about
  const { reducers, sagas, routes, messages } = yield call(
    packageImporter,
    modules
  );

  // Inject reducers
  for (const name in reducers) {
    yield call(injectReducer, name, reducers[name]);
  }

  // Inject sagas
  //    Note: Sagas injected this way must have a [name] prop
  for (const name in sagas) {
    yield call(injectSaga, name, sagas[name]);
  }

  // Inject messages
  yield put(i18nActions.addMessages(messages));

  // Initialize the RouteMap
  const routePaths = yield call(routeGenerator, routes);

  // Push new routes into state, causing the <Routes/> component to re-render
  yield put(Actions.setAvailableRoutes(routePaths));

  // Redirect
  // todo: Calculate a default route based on the available routes
  // yield put(push('/dashboard'));
}
```

**Comment by GuillaumeCisco** [comment]
Hum, I don't see any problem with your code.
What are the version of redux-sagas-injector and redux-reducers-injector you are using?
The error you got should not happen, as the store is default set to an empty object.

Maybe you can put a console.log in the injectReducer method for knowing the value of the store argument for helping me fixing this issue.
Better, can you provide a simple project using this code ?

**Comment by GuillaumeCisco** [comment]
Yes I understand.
The last versions should not be backward incompatible.
We need to investigate further :)

**Comment by GuillaumeCisco** [comment]
Hello @thehig, I've just raleased new versions of redux-reducers-injector and redux-sagas-injector projects. It should solve your problem.
I detected a possible hoisting issue by using default argument with the same name as the argument.
Looks like an issue with the babel transformation plugin : https://babeljs.io/docs/en/babel-plugin-transform-parameters
I'm using an old version in my repository: https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime
Maybe it has been fixed now.
The workaround was simply not to declare the argument as the same name of the default value for avoiding hoisting overlapping.

Please tell me if it fixes your issue ;)

**Comment by thehig** [comment]
I modified the ReduxInjector.js and redux-sagas-injector.js to log out properties (Gist: https://gist.github.com/thehig/08a1bcabab38f0a0bf063280ee679ef1)

The output in my console is this:
![image](https://user-images.githubusercontent.com/96122/48809785-fed4e600-ed1d-11e8-87d8-82e3d89123a2.png)

And my package.json versions:
```
    "redux-sagas-injector": "^0.2.8",
    "redux-reducers-injector": "^0.2.3",
```

**Comment by thehig** [comment]
![image](https://user-images.githubusercontent.com/96122/48839533-b4865000-ed83-11e8-8792-4b60131c346a.png)

This is pretty difficult to extract into a separate project, it's *heavily* integrated. I'll see if I can find some time soon

**Comment by thehig** [comment]
I exported the configured store, passed it as the fourth parameter, but the same error occurs

**Comment by thehig** [comment]
So, I updated my source files ([Gist](https://gist.github.com/thehig/08a1bcabab38f0a0bf063280ee679ef1)) as suggested. Looks like the same error. 

![image](https://user-images.githubusercontent.com/96122/48904934-026c8800-ee58-11e8-8436-1b80dc715fab.png)

**Comment by thehig** [comment]
I tried again to export my store

```
let store;
export default function configureStore(initialState = {}) {
  store = createInjectSagasStore(
    { defaultSagas: sagas },
    reducers,
    initialState,
    enhancer
  );
  return store;
}

export const getStore = () => store;
```

And pass it as the fourth parameter

```
const store = getStore();
// Inject reducers
for (const name in reducers) {
  yield call(injectReducer, name, reducers[name], false, store);
}

// Inject sagas
//    Note: Sagas injected this way must have a [name] prop
for (const name in sagas) {
  yield call(injectSaga, name, sagas[name], false, store);
}
```

And it's now working. I suspect the issue was that the original_store in the redux-reducers-injector was never initialized

**Comment by GuillaumeCisco** [comment]
Thank you @thehig,
It looks like the `original_store` has been correctly initialized but is no longer available in the injectReducer closure. That's why passing it as the fourth parameter ensure the context.

I don't understand why `original_store` is no longer available in the global scope. If someone has an idea, it would be great.
Another way to solve this issue may be to create a class and instantiate it, make this instance gettable, then call methods on this class which refers to the store. But I think it will fail on the server with multiple calls and multiple stores.

Another way to explain this issue is that `original_store` is a global variable and it is overlapped in the saga code. In a few words, the saga code create the store from the reducer code, but it declares a global variable original_store too, and if you are using `use strict;` it can be overriden.

Can you try again, by tweaking the code of the saga by replacing all the `original_store` variable by `sagas_original_store`. I'm curious to see if it works ;)


Anyway, I'm happy it is now working on your machine.

**Comment by GuillaumeCisco** [comment]
Hello @thehig, I was digging around in the code, and just found out that redux-sagas-injector did not correctly referenced the last version or redux-reducers-injector. I think that's why it did not work on your setup.
Furthermore, I found out that as redux-reducers-injector IS a dependency of redux-sagas-injector, we should export `reloadReducer` and `injectReducer` fron redux-sagas-injector for dealing with the same global store.

Can you test your code with the very last version of redux-sags-injector (0.2.9) and importing `injectReducer` from `redux-sagas-injector` as it is allowed now.

I hope it will works correctly without having to pass the store as the fourth argument.

Thank you,

**Comment by thehig** [comment]
Yep, with this latest version I was able to remove the reducers-injector library, import injectReducer from the sagas-injector, and remove the third and fourth parameters, reverting things back to the way it was previously working. 

Thanks for the effort!

**Comment by GuillaumeCisco** [comment]
Thank you @thehig for detecting this behavior ;)
Very happy it works well on your setup :)
